GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "Gabes Cool Blog",
  "author": "Gabe Grieve",
  "url": "https://gabegrieve.com",
  "likes": 100,
  "userId": "6376bfac8b4f4572491a31b5"
}
