GET http://localhost:3003/api/users/
###

POST http://localhost:3003/api/users/
content-type: application/json

{
  "username": "maddog23",
  "name": "Mad Dog",
  "password": "123"
}

###

POST http://localhost:3003/api/users/
content-type: application/json

{
  "username": "M",
  "name": "Mad Dog",
  "password": "123"
}
